// frontend-vue/src/views/LoginPage.vue
<script setup lang="ts">
import { ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { useMessage } from 'naive-ui'
import { useAuthStore } from '@/stores/auth'

const route = useRoute()
const router = useRouter()
const message = useMessage()
const auth = useAuthStore()

const username = ref('')
const password = ref('')
const remember = ref(true)
const loading = ref(false)

async function submit() {
  loading.value = true
  try {
    await auth.login(username.value.trim(), password.value, remember.value)
    message.success('登录成功')
    const redirect = (route.query.redirect as string) || '/dashboard'
    await router.replace(redirect)
  } catch {
    message.error('用户名或密码错误')
  } finally {
    loading.value = false
  }
}
</script>

<template>
  <div style="max-width: 400px; margin: 80px auto">
    <n-h2>登录</n-h2>
    <n-form @submit.prevent="submit">
      <n-form-item label="用户名">
        <n-input v-model:value="username" />
      </n-form-item>
      <n-form-item label="密码">
        <n-input v-model:value="password" type="password" show-password-on="click" />
      </n-form-item>
      <n-form-item label="记住我">
        <n-switch v-model:value="remember" />
      </n-form-item>
      <n-button type="primary" block :loading="loading" attr-type="submit">登录</n-button>
    </n-form>
  </div>
</template>

// frontend/src/pages/LoginPage.tsx
import { useState } from 'react'
import type { FormEvent } from 'react'
import { Navigate, useNavigate } from 'react-router-dom'
import { useAuth } from '../context/AuthContext'
import { Button } from '../components/ui/Button'
import { Card } from '../components/ui/Card'
import { Input } from '../components/ui/Input'
import { Loading } from '../components/ui/Loading'

export function LoginPage() {
  const { ready, needsSetup, user, signIn } = useAuth()
  const navigate = useNavigate()
  const [username, setUsername] = useState('')
  const [password, setPassword] = useState('')
  const [remember, setRemember] = useState(true)
  const [error, setError] = useState<string | null>(null)
  const [pending, setPending] = useState(false)

  if (!ready) {
    return <Loading />
  }

  if (needsSetup) {
    return <Navigate to="/setup" replace />
  }

  if (user?.must_change_password) {
    return <Navigate to="/change-password" replace />
  }

  if (user) {
    return <Navigate to="/dashboard" replace />
  }

  async function onSubmit(e: FormEvent) {
    e.preventDefault()
    setError(null)
    setPending(true)
    try {
      await signIn(username.trim(), password, remember)
      navigate('/dashboard', { replace: true })
    } catch {
      setError('用户名或密码错误')
    } finally {
      setPending(false)
    }
  }

  return (
    <div className="mx-auto flex min-h-screen max-w-lg items-center px-4 py-10">
      <Card title="登录">
        <form className="space-y-4" onSubmit={onSubmit}>
          <Input label="用户名" autoComplete="username" value={username} onChange={(e) => setUsername(e.target.value)} required />
          <Input
            label="密码"
            type="password"
            autoComplete="current-password"
            value={password}
            onChange={(e) => setPassword(e.target.value)}
            required
          />
          <label className="flex items-center gap-2 text-sm text-slate-600">
            <input type="checkbox" checked={remember} onChange={(e) => setRemember(e.target.checked)} />
            记住我（30 天）
          </label>
          {error ? <p className="text-sm text-red-600">{error}</p> : null}
          <Button type="submit" disabled={pending} className="w-full">
            {pending ? '登录中…' : '登录'}
          </Button>
        </form>
      </Card>
    </div>
  )
}
