// frontend/src/pages/ChangePasswordPage.tsx
import { useState } from 'react'
import type { FormEvent } from 'react'
import { useNavigate } from 'react-router-dom'
import * as api from '../api/api'
import { useAuth } from '../context/AuthContext'
import { Button } from '../components/ui/Button'
import { Card } from '../components/ui/Card'
import { Input } from '../components/ui/Input'

export function ChangePasswordPage() {
  const { user, refreshUser } = useAuth()
  const navigate = useNavigate()
  const [current, setCurrent] = useState('')
  const [next, setNext] = useState('')
  const [error, setError] = useState<string | null>(null)
  const [pending, setPending] = useState(false)

  async function onSubmit(e: FormEvent) {
    e.preventDefault()
    setError(null)
    setPending(true)
    try {
      await api.changePassword(current, next)
      await refreshUser()
      navigate('/dashboard', { replace: true })
    } catch {
      setError('请检查当前密码是否符合要求（新密码至少 8 位）')
    } finally {
      setPending(false)
    }
  }

  return (
    <div className="mx-auto max-w-lg px-4 py-8">
      <Card title="修改密码">
        <p className="mb-4 text-sm text-slate-600">
          {user?.must_change_password ? '首次登录需要修改密码后才能继续使用。' : '更新登录密码。'}
        </p>
        <form className="space-y-4" onSubmit={onSubmit}>
          <Input label="当前密码" type="password" value={current} onChange={(e) => setCurrent(e.target.value)} required />
          <Input
            label="新密码"
            type="password"
            value={next}
            onChange={(e) => setNext(e.target.value)}
            required
            minLength={8}
          />
          {error ? <p className="text-sm text-red-600">{error}</p> : null}
          <Button type="submit" disabled={pending} className="w-full">
            {pending ? '保存中…' : '保存'}
          </Button>
        </form>
      </Card>
    </div>
  )
}

// frontend-vue/src/views/ChangePasswordPage.vue
<script setup lang="ts">
import { ref } from 'vue'
import { useRouter } from 'vue-router'
import { useMessage } from 'naive-ui'
import * as authApi from '@/api/auth'
import { useAuthStore } from '@/stores/auth'

const router = useRouter()
const message = useMessage()
const auth = useAuthStore()

const current = ref('')
const next = ref('')
const loading = ref(false)

async function submit() {
  loading.value = true
  try {
    await authApi.changePassword(current.value, next.value)
    message.success('已更新密码')
    await auth.refreshUser()
    await router.replace('/dashboard')
  } catch {
    message.error('当前密码不正确或请求失败')
  } finally {
    loading.value = false
  }
}
</script>

<template>
  <div style="max-width: 400px; margin: 80px auto">
    <n-h2>修改密码</n-h2>
    <n-alert type="info" style="margin-bottom: 16px">登录后需修改密码方可继续使用。</n-alert>
    <n-form @submit.prevent="submit">
      <n-form-item label="当前密码">
        <n-input v-model:value="current" type="password" show-password-on="click" />
      </n-form-item>
      <n-form-item label="新密码（至少 8 位）">
        <n-input v-model:value="next" type="password" show-password-on="click" />
      </n-form-item>
      <n-button type="primary" block :loading="loading" attr-type="submit">保存</n-button>
    </n-form>
  </div>
</template>
